/**
 * Part 11 — Posting Engine Types
 * 
 * Core types for stock ledger, general ledger, and period lock services.
 */

// ═══════════════════════════════════════════════════════════════════════════
// STOCK MOVEMENT TYPES
// ═══════════════════════════════════════════════════════════════════════════

export type StockMovementType = 
  | 'GRN'                    // Goods Receipt Note (inbound)
  | 'ISSUE'                  // Material issue (outbound)
  | 'TRANSFER_OUT'           // Transfer to another store
  | 'TRANSFER_IN'            // Transfer from another store
  | 'ADJUSTMENT'             // Stock adjustment
  | 'REVERSAL'               // Reversal of a previous movement
  | 'OPENING_BALANCE';       // Initial stock load

export interface StockMovementInput {
  projectId: number;
  storeId: number;
  binId?: number;
  itemId: number;
  batchId?: number;
  movementType: StockMovementType;
  movementDate: Date;
  quantity: number;           // ALWAYS positive; sign derived from type
  uom: string;
  rate?: number;              // Required for inbound; derived for outbound
  source: {
    type: string;
    id: number;
    lineId?: number;
  };
  costDestination?: {
    costCodeId?: number;
    wbsId?: number;
    boqItemId?: number;
    equipmentId?: number;
  };
  reversalOfId?: number;
  allowNegative?: boolean;    // Honoured only if project config permits
}

export interface StockLedgerRow {
  id: number;
  projectId: number;
  storeId: number;
  binId?: number;
  itemId: number;
  batchId?: number;
  movementType: StockMovementType;
  movementDate: string;
  quantity: number;           // Signed
  uom: string;
  rate: number;
  value: number;              // Signed
  balanceQty: number;
  balanceValue: number;
  sourceType: string;
  sourceId: number;
  sourceLineId?: number;
  reversalOfId?: number;
  costCodeId?: number;
  wbsId?: number;
  boqItemId?: number;
  equipmentId?: number;
  createdBy: number;
  createdAt: string;
  prevHash: string;
  rowHash: string;
}

export interface StockPostingResult {
  ledgerId: number;
  balanceQty: number;
  balanceValue: number;
  appliedRate: number;
}

// ═══════════════════════════════════════════════════════════════════════════
// VALUATION TYPES
// ═══════════════════════════════════════════════════════════════════════════

export type ValuationMethod = 'WEIGHTED_AVERAGE' | 'FIFO' | 'BATCH_SPECIFIC';

export interface IssueRateParams {
  method: ValuationMethod;
  projectId: number;
  storeId: number;
  itemId: number;
  batchId?: number;
  qty: number;
  openQty: number;
  openVal: number;
}

export interface FifoLayer {
  id: number;
  ledgerId: number;
  rate: number;
  originalQty: number;
  balanceQty: number;
  consumedQty: number;
}

// ═══════════════════════════════════════════════════════════════════════════
// GL POSTING TYPES
// ═══════════════════════════════════════════════════════════════════════════

export type VoucherType = 'JV' | 'PAYMENT' | 'RECEIPT' | 'CONTRA' | 'SALES' | 'PURCHASE' | 'PROVISION';
export type VoucherSide = 'D' | 'C';
export type VoucherStatus = 'POSTED' | 'REVERSED' | 'CANCELLED';

export interface PostingRule {
  id: number;
  ruleCode: string;
  eventType: string;
  companyId?: number;
  conditionExpr?: string;
  lineNo: number;
  accountResolver: AccountResolverType;
  resolverArgs?: Record<string, any>;
  side: VoucherSide;
  amountExpr: string;
  dimensionMap: Record<string, string>;
  narrationTpl?: string;
  effectiveFrom: string;
  effectiveTo?: string;
  isActive: boolean;
}

export type AccountResolverType = 
  | 'FIXED'
  | 'ITEM_CATEGORY_ACCOUNT'
  | 'VENDOR_CONTROL'
  | 'CLIENT_CONTROL'
  | 'COST_CODE_ACCOUNT'
  | 'TAX_ACCOUNT'
  | 'PROJECT_WIP'
  | 'EQUIPMENT_ACCOUNT'
  | 'PAYROLL_COMPONENT'
  | 'GRNI';

export interface VoucherLineDraft {
  lineNo: number;
  accountId: number;
  accountCode: string;
  side: VoucherSide;
  amount: number;
  projectId?: number;
  costCodeId?: number;
  wbsId?: number;
  costCentreId?: number;
  equipmentId?: number;
  partyType?: string;
  partyId?: number;
  narration?: string;
  referenceType?: string;
  referenceId?: number;
}

export interface VoucherDraft {
  voucherNo: string;
  voucherType: VoucherType;
  voucherDate: string;
  companyId: number;
  projectId?: number;
  fiscalYear: string;
  periodMonth: string;
  sourceType?: string;
  sourceId?: number;
  totalDebit: number;
  totalCredit: number;
  status: VoucherStatus;
  reversalOfId?: number;
  reversalReason?: string;
  isAutoGenerated: boolean;
  narration?: string;
  postedBy: number;
  postedAt: string;
}

export interface VoucherRow extends VoucherDraft {
  id: number;
  rowHash: string;
}

export interface VoucherLineRow extends VoucherLineDraft {
  id: number;
  voucherId: number;
}

// ═══════════════════════════════════════════════════════════════════════════
// FINANCIAL DIMENSION TYPES
// ═══════════════════════════════════════════════════════════════════════════

export interface DimensionSet {
  projectId?: number;
  wbsId?: number;
  costCodeId?: number;
  costCentreId?: number;
  equipmentId?: number;
  partyType?: string;
  partyId?: number;
}

export interface FinancialDimensionRow {
  id: number;
  accountId: number;
  projectId?: number;
  costCodeId?: number;
  wbsId?: number;
  costCentreId?: number;
  equipmentId?: number;
  partyType?: string;
  partyId?: number;
  isValid: boolean;
}

// ═══════════════════════════════════════════════════════════════════════════
// PERIOD LOCK TYPES
// ═══════════════════════════════════════════════════════════════════════════

export type PeriodModule = 'ALL' | 'FINANCE' | 'STOCK' | 'PAYROLL' | 'BILLING';
export type PeriodStatus = 'OPEN' | 'SOFT_CLOSED' | 'CLOSED' | 'REOPENED';

export interface PeriodLockRow {
  id: number;
  companyId: number;
  periodMonth: string;        // 'YYYY-MM'
  module: PeriodModule;
  status: PeriodStatus;
  closedBy?: number;
  closedAt?: string;
  reopenedBy?: number;
  reopenedAt?: string;
  reopenReason?: string;
  reopenExpiresAt?: string;
}

// ═══════════════════════════════════════════════════════════════════════════
// POSTING RULE SEED TYPES
// ═══════════════════════════════════════════════════════════════════════════

export interface PostingRuleSeed {
  ruleCode: string;
  eventType: string;
  lineNo: number;
  side: VoucherSide;
  accountResolver: AccountResolverType;
  resolverArgs?: Record<string, any>;
  amountExpr: string;
  dimensionMap: Record<string, string>;
  narrationTpl?: string;
  conditionExpr?: string;
}

// ═══════════════════════════════════════════════════════════════════════════
// ERROR TYPES
// ═══════════════════════════════════════════════════════════════════════════

export class PostingError extends Error {
  constructor(
    public code: string,
    public details: Record<string, any>
  ) {
    super(`${code}: ${JSON.stringify(details)}`);
    this.name = 'PostingError';
  }
}

export class InsufficientStockError extends PostingError {
  constructor(details: {
    itemCode: string;
    itemName: string;
    store: number;
    available: number;
    requested: number;
    shortfall: number;
    uom: string;
  }) {
    super('INSUFFICIENT_STOCK', details);
  }
}

export class PeriodClosedError extends PostingError {
  constructor(details: {
    period: string;
    module: string;
    closedAt?: string;
    remedy: string;
  }) {
    super('PERIOD_CLOSED', details);
  }
}

export class VoucherUnbalancedError extends PostingError {
  constructor(details: {
    eventType: string;
    debit: number;
    credit: number;
    difference: number;
    lines: VoucherLineDraft[];
  }) {
    super('VOUCHER_UNBALANCED', details);
  }
}

export class DimensionError extends PostingError {
  constructor(
    code: 'DIMENSION_REQUIRED' | 'DIMENSION_NOT_ALLOWED' | 'DIMENSION_COMBINATION_INVALID' | 'COST_CODE_NOT_POSTABLE',
    details: Record<string, any>
  ) {
    super(code, details);
  }
}
