/**
 * Part 14 — KPI & Alert Seed Data
 * 
 * Seeds the initial set of KPI definitions and alert rules.
 * In production, these would be loaded from the database.
 */

import { KPISeedData, AlertRuleSeedData } from './types';

export const KPI_SEED_DATA: KPISeedData[] = [
  // Project KPIs
  {
    kpiKey: 'project.physical_progress',
    kpiName: 'Physical Progress',
    module: 'project',
    description: 'Percentage of physical work completed vs planned',
    calculationType: 'RATIO',
    valueType: 'PERCENT',
    unit: '%',
    aggregationLevel: 'PROJECT',
    sourceDefinition: {
      tables: ['measurement_book'],
      aggregate: { field: 'certified_value', function: 'SUM' },
    },
    targetSource: 'PLAN',
    goodDirection: 'UP',
    thresholdGreen: 90,
    thresholdAmber: 70,
    refreshStrategy: 'EVENT',
    requiredPermission: 'project.project.view',
    drillRoute: '/project/progress',
  },
  {
    kpiKey: 'project.cost_variance',
    kpiName: 'Cost Variance',
    module: 'project',
    description: 'Variance between actual cost and budget',
    calculationType: 'VARIANCE',
    valueType: 'PERCENT',
    unit: '%',
    aggregationLevel: 'PROJECT',
    sourceDefinition: {
      tables: ['project_cost', 'project_budget'],
      aggregate: { field: 'variance_percent', function: 'AVG' },
    },
    targetSource: 'BUDGET',
    goodDirection: 'DOWN',
    thresholdGreen: 5,
    thresholdAmber: 10,
    refreshStrategy: 'EVENT',
    requiredPermission: 'project.project.view',
    drillRoute: '/project/cost',
  },

  // Procurement KPIs
  {
    kpiKey: 'procurement.po_pending_count',
    kpiName: 'Pending Purchase Orders',
    module: 'procurement',
    description: 'Number of purchase orders awaiting approval or delivery',
    calculationType: 'COUNT',
    valueType: 'COUNT',
    aggregationLevel: 'PROJECT',
    sourceDefinition: {
      tables: ['purchase_order'],
      filters: [{ field: 'status', operator: 'IN', value: ['APPROVED', 'RELEASED'] }],
      aggregate: { field: 'id', function: 'COUNT' },
    },
    goodDirection: 'DOWN',
    thresholdGreen: 5,
    thresholdAmber: 15,
    refreshStrategy: 'EVENT',
    requiredPermission: 'procure.po.view',
    drillRoute: '/procurement/po',
  },
  {
    kpiKey: 'procurement.po_value_approved',
    kpiName: 'Approved PO Value',
    module: 'procurement',
    description: 'Total value of approved purchase orders',
    calculationType: 'SUM',
    valueType: 'CURRENCY',
    unit: 'INR',
    aggregationLevel: 'PROJECT',
    sourceDefinition: {
      tables: ['purchase_order'],
      filters: [{ field: 'status', operator: '=', value: 'APPROVED' }],
      aggregate: { field: 'total_value', function: 'SUM' },
    },
    targetSource: 'BUDGET',
    goodDirection: 'TARGET',
    thresholdGreen: 10,
    thresholdAmber: 20,
    refreshStrategy: 'EVENT',
    requiredPermission: 'procure.po.view',
    drillRoute: '/procurement/po',
  },

  // Store KPIs
  {
    kpiKey: 'store.stock_value',
    kpiName: 'Stock Value',
    module: 'store',
    description: 'Total value of inventory on hand',
    calculationType: 'SUM',
    valueType: 'CURRENCY',
    unit: 'INR',
    aggregationLevel: 'PROJECT',
    sourceDefinition: {
      tables: ['stock_ledger'],
      aggregate: { field: 'balance_value', function: 'SUM' },
    },
    goodDirection: 'TARGET',
    refreshStrategy: 'EVENT',
    requiredPermission: 'store.stock.view',
    drillRoute: '/store/stock',
  },
  {
    kpiKey: 'store.low_stock_count',
    kpiName: 'Low Stock Items',
    module: 'store',
    description: 'Number of items below reorder level',
    calculationType: 'COUNT',
    valueType: 'COUNT',
    aggregationLevel: 'PROJECT',
    sourceDefinition: {
      tables: ['stock_ledger', 'item_master'],
      joins: [{ type: 'INNER', table: 'item_master', on: 'item_id' }],
      filters: [{ field: 'balance_qty', operator: '<', value: 'reorder_level' }],
      aggregate: { field: 'item_id', function: 'COUNT' },
    },
    goodDirection: 'DOWN',
    thresholdGreen: 5,
    thresholdAmber: 15,
    refreshStrategy: 'EVENT',
    requiredPermission: 'store.stock.view',
    drillRoute: '/store/low-stock',
  },

  // Billing KPIs
  {
    kpiKey: 'billing.certified_value',
    kpiName: 'Certified Billing Value',
    module: 'billing',
    description: 'Total value of certified RA bills',
    calculationType: 'SUM',
    valueType: 'CURRENCY',
    unit: 'INR',
    aggregationLevel: 'PROJECT',
    sourceDefinition: {
      tables: ['ra_bill'],
      filters: [{ field: 'status', operator: '=', value: 'CERTIFIED' }],
      aggregate: { field: 'certified_value', function: 'SUM' },
    },
    targetSource: 'PLAN',
    goodDirection: 'UP',
    thresholdGreen: 90,
    thresholdAmber: 70,
    refreshStrategy: 'EVENT',
    requiredPermission: 'bill.client.view',
    drillRoute: '/billing/ra-bills',
  },
  {
    kpiKey: 'billing.pending_count',
    kpiName: 'Pending Bills',
    module: 'billing',
    description: 'Number of bills awaiting certification',
    calculationType: 'COUNT',
    valueType: 'COUNT',
    aggregationLevel: 'PROJECT',
    sourceDefinition: {
      tables: ['ra_bill'],
      filters: [{ field: 'status', operator: 'IN', value: ['SUBMITTED', 'UNDER_REVIEW'] }],
      aggregate: { field: 'id', function: 'COUNT' },
    },
    goodDirection: 'DOWN',
    thresholdGreen: 2,
    thresholdAmber: 5,
    refreshStrategy: 'EVENT',
    requiredPermission: 'bill.client.view',
    drillRoute: '/billing/pending',
  },

  // Finance KPIs
  {
    kpiKey: 'finance.cash_position',
    kpiName: 'Cash Position',
    module: 'finance',
    description: 'Current cash balance',
    calculationType: 'SUM',
    valueType: 'CURRENCY',
    unit: 'INR',
    aggregationLevel: 'PROJECT',
    sourceDefinition: {
      tables: ['cash_balance'],
      aggregate: { field: 'balance', function: 'SUM' },
    },
    goodDirection: 'UP',
    thresholdGreen: 1000000,
    thresholdAmber: 500000,
    refreshStrategy: 'EVENT',
    requiredPermission: 'finance.voucher.view',
    drillRoute: '/finance/cash',
  },

  // HR KPIs
  {
    kpiKey: 'hr.headcount',
    kpiName: 'Headcount',
    module: 'hr',
    description: 'Total number of active employees',
    calculationType: 'COUNT',
    valueType: 'COUNT',
    aggregationLevel: 'PROJECT',
    sourceDefinition: {
      tables: ['employee'],
      filters: [{ field: 'status', operator: '=', value: 'ACTIVE' }],
      aggregate: { field: 'id', function: 'COUNT' },
    },
    goodDirection: 'TARGET',
    refreshStrategy: 'EVENT',
    requiredPermission: 'hr.employee.view',
    drillRoute: '/hr/employees',
  },
  {
    kpiKey: 'hr.attendance_percent',
    kpiName: 'Attendance Percentage',
    module: 'hr',
    description: 'Average attendance percentage',
    calculationType: 'AVG',
    valueType: 'PERCENT',
    unit: '%',
    aggregationLevel: 'PROJECT',
    sourceDefinition: {
      tables: ['attendance'],
      aggregate: { field: 'attendance_percent', function: 'AVG' },
    },
    goodDirection: 'UP',
    thresholdGreen: 95,
    thresholdAmber: 85,
    refreshStrategy: 'EVENT',
    requiredPermission: 'hr.attendance.view',
    drillRoute: '/hr/attendance',
  },
];

export const ALERT_RULE_SEED_DATA: AlertRuleSeedData[] = [
  // Procurement Alerts
  {
    ruleCode: 'PO-OVERDUE',
    ruleName: 'Purchase Order Overdue',
    module: 'procurement',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'delivery_date', operator: '<', value: 'today' },
      { field: 'grn_status', operator: '!=', value: 'COMPLETE' },
    ],
    severity: 'HIGH',
    messageTemplate: 'PO {{po_number}} is overdue for delivery. Expected: {{delivery_date}}',
    targetRule: 'RESPONSIBILITY',
    cooldownMinutes: 1440, // 24 hours
  },
  {
    ruleCode: 'PO-PARTIAL',
    ruleName: 'PO Partially Received',
    module: 'procurement',
    triggerType: 'EVENT',
    triggerEvent: 'grn.posted',
    condition: [
      { field: 'received_quantity', operator: '<', value: 'ordered_quantity' },
      { field: 'days_since_po', operator: '>', value: 30 },
    ],
    severity: 'MEDIUM',
    messageTemplate: 'PO {{po_number}} is partially received. Balance pending for {{days_since_po}} days',
    targetRule: 'RESPONSIBILITY',
  },

  // Store Alerts
  {
    ruleCode: 'STOCK-REORDER',
    ruleName: 'Stock Below Reorder Level',
    module: 'store',
    triggerType: 'EVENT',
    triggerEvent: 'stock.moved',
    condition: [
      { field: 'balance_qty', operator: '<', value: 'reorder_level' },
    ],
    severity: 'MEDIUM',
    messageTemplate: 'Item {{item_code}} is below reorder level. Current: {{balance_qty}}, Reorder: {{reorder_level}}',
    targetRule: 'RESPONSIBILITY',
  },
  {
    ruleCode: 'STOCK-NEGATIVE',
    ruleName: 'Negative Stock',
    module: 'store',
    triggerType: 'EVENT',
    triggerEvent: 'stock.moved',
    condition: [
      { field: 'balance_qty', operator: '<', value: 0 },
    ],
    severity: 'CRITICAL',
    messageTemplate: 'Item {{item_code}} has negative stock: {{balance_qty}} {{uom}}',
    targetRule: 'RESPONSIBILITY',
  },
  {
    ruleCode: 'STOCK-NONMOVING',
    ruleName: 'Non-Moving Stock',
    module: 'store',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'days_since_last_movement', operator: '>', value: 90 },
      { field: 'stock_value', operator: '>', value: 100000 },
    ],
    severity: 'LOW',
    messageTemplate: 'Item {{item_code}} has not moved in {{days_since_last_movement}} days. Value: ₹{{stock_value}}',
    targetRule: 'RESPONSIBILITY',
    cooldownMinutes: 10080, // 7 days
  },

  // Finance Alerts
  {
    ruleCode: 'BUDGET-80',
    ruleName: 'Budget 80% Reached',
    module: 'finance',
    triggerType: 'EVENT',
    triggerEvent: 'voucher.posted',
    condition: [
      { field: 'budget_utilization_percent', operator: '>=', value: 80 },
      { field: 'budget_utilization_percent', operator: '<', value: 100 },
    ],
    severity: 'MEDIUM',
    messageTemplate: 'Cost head {{cost_code}} has reached {{budget_utilization_percent}}% of budget',
    targetRule: 'MANAGER',
  },
  {
    ruleCode: 'BUDGET-EXCEEDED',
    ruleName: 'Budget Exceeded',
    module: 'finance',
    triggerType: 'EVENT',
    triggerEvent: 'voucher.posted',
    condition: [
      { field: 'budget_utilization_percent', operator: '>', value: 100 },
    ],
    severity: 'CRITICAL',
    messageTemplate: 'Cost head {{cost_code}} has exceeded budget by {{overrun_amount}}',
    targetRule: 'MANAGER',
  },
  {
    ruleCode: 'CASH-NEGATIVE',
    ruleName: 'Negative Cash Projection',
    module: 'finance',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'projected_cash_30_days', operator: '<', value: 0 },
    ],
    severity: 'CRITICAL',
    messageTemplate: 'Project cash position projected to be negative in 30 days: ₹{{projected_cash_30_days}}',
    targetRule: 'MANAGER',
    cooldownMinutes: 1440,
  },

  // Project Alerts
  {
    ruleCode: 'PROJECT-DELAYED',
    ruleName: 'Project Delayed',
    module: 'project',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'progress_variance_percent', operator: '<', value: -10 },
    ],
    severity: 'HIGH',
    messageTemplate: 'Project is {{progress_variance_percent}}% behind schedule',
    targetRule: 'MANAGER',
    cooldownMinutes: 10080,
  },
  {
    ruleCode: 'MILESTONE-RISK',
    ruleName: 'Milestone at Risk',
    module: 'project',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'days_to_milestone', operator: '<=', value: 7 },
      { field: 'milestone_progress_percent', operator: '<', value: 80 },
    ],
    severity: 'HIGH',
    messageTemplate: 'Milestone {{milestone_name}} due in {{days_to_milestone}} days is at {{milestone_progress_percent}}% complete',
    targetRule: 'MANAGER',
  },

  // Billing Alerts
  {
    ruleCode: 'BILL-PENDING',
    ruleName: 'Bill Pending Beyond SLA',
    module: 'billing',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'days_since_submission', operator: '>', value: 'sla_days' },
      { field: 'status', operator: 'IN', value: ['SUBMITTED', 'UNDER_REVIEW'] },
    ],
    severity: 'MEDIUM',
    messageTemplate: 'RA Bill {{bill_number}} has been pending for {{days_since_submission}} days',
    targetRule: 'RESPONSIBILITY',
  },
  {
    ruleCode: 'RECEIVABLE-OVERDUE',
    ruleName: 'Receivable Overdue',
    module: 'billing',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'days_overdue', operator: '>', value: 0 },
    ],
    severity: 'HIGH',
    messageTemplate: 'Invoice {{invoice_number}} is {{days_overdue}} days overdue. Amount: ₹{{outstanding_amount}}',
    targetRule: 'RESPONSIBILITY',
    cooldownMinutes: 1440,
  },
  {
    ruleCode: 'RECEIVABLE-90',
    ruleName: 'Receivable 90+ Days',
    module: 'billing',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'days_overdue', operator: '>=', value: 90 },
    ],
    severity: 'CRITICAL',
    messageTemplate: 'Invoice {{invoice_number}} is {{days_overdue}} days overdue. Amount: ₹{{outstanding_amount}}',
    targetRule: 'MANAGER',
  },

  // Quality Alerts
  {
    ruleCode: 'NCR-OVERDUE',
    ruleName: 'NCR Overdue',
    module: 'quality',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'days_since_raised', operator: '>', value: 'closure_sla_days' },
      { field: 'status', operator: '!=', value: 'CLOSED' },
    ],
    severity: 'HIGH',
    messageTemplate: 'NCR {{ncr_number}} is overdue for closure. Raised {{days_since_raised}} days ago',
    targetRule: 'RESPONSIBILITY',
  },
  {
    ruleCode: 'TEST-FAILED',
    ruleName: 'Test Failed',
    module: 'quality',
    triggerType: 'EVENT',
    triggerEvent: 'test.completed',
    condition: [
      { field: 'result', operator: '=', value: 'FAILED' },
    ],
    severity: 'CRITICAL',
    messageTemplate: '{{test_type}} test failed for {{item_code}}. Result: {{test_result}}',
    targetRule: 'RESPONSIBILITY',
  },

  // Safety Alerts
  {
    ruleCode: 'PERMIT-EXPIRED',
    ruleName: 'Work Permit Expired',
    module: 'safety',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'expiry_date', operator: '<', value: 'today' },
      { field: 'work_status', operator: '=', value: 'IN_PROGRESS' },
    ],
    severity: 'CRITICAL',
    messageTemplate: 'Work permit {{permit_number}} has expired but work is still in progress',
    targetRule: 'RESPONSIBILITY',
  },
  {
    ruleCode: 'INCIDENT-REPORTED',
    ruleName: 'Safety Incident Reported',
    module: 'safety',
    triggerType: 'EVENT',
    triggerEvent: 'incident.reported',
    condition: [],
    severity: 'CRITICAL',
    messageTemplate: 'Safety incident reported: {{incident_type}} at {{location}}',
    targetRule: 'MANAGER',
  },

  // Workflow Alerts
  {
    ruleCode: 'APPROVAL-SLA',
    ruleName: 'Approval SLA Breach',
    module: 'workflow',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'sla_status', operator: '=', value: 'OVERDUE' },
    ],
    severity: 'HIGH',
    messageTemplate: '{{document_type}} {{document_number}} approval is overdue by {{days_overdue}} days',
    targetRule: 'MANAGER',
    cooldownMinutes: 1440,
  },

  // Compliance Alerts
  {
    ruleCode: 'CONTRACT-EXPIRY',
    ruleName: 'Contract Expiring',
    module: 'admin',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'days_to_expiry', operator: '<=', value: 30 },
      { field: 'days_to_expiry', operator: '>', value: 0 },
    ],
    severity: 'MEDIUM',
    messageTemplate: 'Contract {{contract_number}} expires in {{days_to_expiry}} days',
    targetRule: 'RESPONSIBILITY',
    cooldownMinutes: 10080,
  },
  {
    ruleCode: 'DOC-EXPIRY',
    ruleName: 'Document Expiring',
    module: 'admin',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'days_to_expiry', operator: '<=', value: 30 },
      { field: 'days_to_expiry', operator: '>', value: 0 },
    ],
    severity: 'HIGH',
    messageTemplate: '{{document_type}} {{document_number}} expires in {{days_to_expiry}} days',
    targetRule: 'RESPONSIBILITY',
    cooldownMinutes: 10080,
  },
  {
    ruleCode: 'INSURANCE-EXPIRY',
    ruleName: 'Insurance Expiring',
    module: 'admin',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'days_to_expiry', operator: '<=', value: 30 },
      { field: 'days_to_expiry', operator: '>', value: 0 },
    ],
    severity: 'HIGH',
    messageTemplate: 'Insurance policy {{policy_number}} expires in {{days_to_expiry}} days',
    targetRule: 'MANAGER',
  },

  // Equipment Alerts
  {
    ruleCode: 'MAINT-DUE',
    ruleName: 'Maintenance Due',
    module: 'equipment',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'days_to_maintenance', operator: '<=', value: 7 },
      { field: 'days_to_maintenance', operator: '>', value: 0 },
    ],
    severity: 'MEDIUM',
    messageTemplate: 'Equipment {{equipment_code}} maintenance due in {{days_to_maintenance}} days',
    targetRule: 'RESPONSIBILITY',
  },
  {
    ruleCode: 'MAINT-OVERDUE',
    ruleName: 'Maintenance Overdue',
    module: 'equipment',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'days_overdue', operator: '>', value: 0 },
    ],
    severity: 'HIGH',
    messageTemplate: 'Equipment {{equipment_code}} maintenance is {{days_overdue}} days overdue',
    targetRule: 'MANAGER',
  },
  {
    ruleCode: 'EQUIP-BREAKDOWN',
    ruleName: 'Equipment Breakdown',
    module: 'equipment',
    triggerType: 'EVENT',
    triggerEvent: 'equipment.breakdown',
    condition: [],
    severity: 'HIGH',
    messageTemplate: 'Equipment {{equipment_code}} has broken down. Downtime: {{downtime_hours}} hours',
    targetRule: 'MANAGER',
  },
  {
    ruleCode: 'FUEL-ANOMALY',
    ruleName: 'Fuel Consumption Anomaly',
    module: 'equipment',
    triggerType: 'EVENT',
    triggerEvent: 'fuel.consumed',
    condition: [
      { field: 'consumption_variance_percent', operator: '>', value: 20 },
    ],
    severity: 'MEDIUM',
    messageTemplate: 'Equipment {{equipment_code}} fuel consumption is {{consumption_variance_percent}}% above norm',
    targetRule: 'RESPONSIBILITY',
  },

  // HR Alerts
  {
    ruleCode: 'ATTENDANCE-ANOMALY',
    ruleName: 'Attendance Anomaly',
    module: 'hr',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'attendance_variance_percent', operator: '<', value: -20 },
    ],
    severity: 'MEDIUM',
    messageTemplate: 'Attendance anomaly detected: {{attendance_variance_percent}}% below expected',
    targetRule: 'MANAGER',
    cooldownMinutes: 1440,
  },
  {
    ruleCode: 'DPR-MISSING',
    ruleName: 'DPR Not Submitted',
    module: 'execution',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'dpr_submitted', operator: '=', value: false },
      { field: 'current_time', operator: '>', value: 'cutoff_time' },
    ],
    severity: 'MEDIUM',
    messageTemplate: 'DPR for {{date}} not submitted by cutoff time',
    targetRule: 'RESPONSIBILITY',
  },
  {
    ruleCode: 'MB-PENDING',
    ruleName: 'MB Pending Certification',
    module: 'execution',
    triggerType: 'SCHEDULE',
    condition: [
      { field: 'days_since_submission', operator: '>', value: 'sla_days' },
      { field: 'status', operator: '=', value: 'SUBMITTED' },
    ],
    severity: 'MEDIUM',
    messageTemplate: 'MB {{mb_number}} has been pending certification for {{days_since_submission}} days',
    targetRule: 'RESPONSIBILITY',
  },

  // System Alerts
  {
    ruleCode: 'SOD-VIOLATION',
    ruleName: 'Segregation of Duties Violation',
    module: 'admin',
    triggerType: 'EVENT',
    triggerEvent: 'permission.changed',
    condition: [
      { field: 'sod_violation_detected', operator: '=', value: true },
    ],
    severity: 'HIGH',
    messageTemplate: 'SoD violation detected for user {{user_id}}: {{violation_description}}',
    targetRule: 'MANAGER',
  },
  {
    ruleCode: 'BACKUP-FAILED',
    ruleName: 'Backup Failed',
    module: 'admin',
    triggerType: 'EVENT',
    triggerEvent: 'backup.failed',
    condition: [],
    severity: 'CRITICAL',
    messageTemplate: 'Scheduled backup failed: {{error_message}}',
    targetRule: 'MANAGER',
  },
];
