/* Part 1 · People & Finance — Attendance, HR & People, Payroll */
import { useMemo, useState } from "react";
import { useERP, dStr } from "../store";
import { Widget, Pill, Bar, cx, useToast } from "../ui";
import { PageHead, Seg, FilterBar, DataTable, Drawer, Btn, Stat } from "./core";
import type { Col } from "./core";
import { printDocument } from "../print";
import { ICheck, IXCircle, IPrinter, ICamera, IEye } from "../icons";

const L = (v: number) => "₹" + v.toLocaleString("en-IN", { maximumFractionDigits: 2 });

/* ══════════ ATTENDANCE ══════════ */
export function AttendancePage() {
  const { s, setS, can, log, notify, user } = useERP();
  const toast = useToast();
  const [tab, setTab] = useState<"today" | "punches" | "approvals">("today");

  const pending = s.attendance.filter((a) => a.appr === "Pending");

  const decide = (a: any, ok: boolean) => {
    setS((p) => ({ ...p, attendance: p.attendance.map((x) => x.id === a.id ? { ...x, appr: ok ? "Approved" : "Rejected" } : x) }));
    log("Attendance", ok ? "Attendance Approved" : "Attendance Rejected", a.empId, `${a.name} · ${a.hours || 8} hrs · ${a.project}`);
    notify("hr", `${a.name}'s attendance ${ok ? "approved" : "rejected"} — flows to payroll`);
    toast(ok ? "success" : "info", `${a.name} ${ok ? "approved" : "rejected"}`);
  };

  const aCols: Col[] = [
    { key: "empId", label: "Employee", render: (a) => <div><p className="text-[12.5px] font-semibold text-ink-900">{a.name}</p><p className="text-[10.5px] num text-ink-400">{a.empId}</p></div> },
    { key: "project", label: "Project", render: (a) => <span className="num text-[12px] text-ink-500">{a.project}</span> },
    { key: "hours", label: "Hours", align: "right", sort: (a) => a.hours, render: (a) => <span className="num text-[12px] font-semibold">{a.hours || "—"}</span> },
    { key: "ot", label: "OT (hrs)", align: "right", sort: (a) => a.ot, render: (a) => <span className={cx("num text-[12px]", a.ot > 0 ? "text-brand-700 font-semibold" : "text-ink-400")}>{a.ot || "—"}</span> },
    { key: "status", label: "Status", render: (a) => <Pill value={a.status} /> },
    { key: "appr", label: "Approval", render: (a) => <Pill value={a.appr} pulse={a.appr === "Pending"} />, csv: (a) => a.appr },
    { key: "act", label: "", render: (a: any) => a.appr === "Pending" && can("attendance", "approve") ? (
      <span className="flex gap-1 justify-end">
        <Btn sm kind="ok" onClick={(e: any) => { e.stopPropagation(); decide(a, true); }}><ICheck size={11} /> Approve</Btn>
        <Btn sm kind="danger" onClick={(e: any) => { e.stopPropagation(); decide(a, false); }}><IXCircle size={11} /></Btn>
      </span>) : null },
  ];

  const printRegister = () => {
    const emps = s.employees;
    const days = Array.from({ length: 26 }, (_, i) => i + 1);
    printDocument({
      title: "Monthly Attendance Register", docNo: "ATT-" + dStr(0).replace(/\s/g, ""), date: dStr(0), orientation: "landscape", paper: "a3",
      meta: [["Period", dStr(0).slice(3)], ["Department", "All"], ["Generated By", user.name]],
      cols: [
        { label: "Employee" }, { label: "Designation" }, { label: "Project" },
        ...days.map((d): { label: string; align?: "center" } => ({ label: String(d), align: "center" })),
        { label: "P", align: "right" }, { label: "A", align: "right" }, { label: "L", align: "right" }, { label: "OT", align: "right" },
      ],
      rows: emps.map((e) => {
        const seedN = e.id.charCodeAt(e.id.length - 1);
        const marks = days.map((d) => ((d + seedN) % 9 === 0 ? "A" : (d + seedN) % 7 === 0 ? "L" : "P"));
        const P = marks.filter((m) => m === "P").length, A = marks.filter((m) => m === "A").length, Lv = marks.filter((m) => m === "L").length;
        return [`${e.id} · ${e.name}`, e.designation, e.project, ...marks, P, A, Lv, (seedN % 5) * 2];
      }),
      remarks: "Legend — P: Present · A: Absent · L: Leave · HD: Half Day. OT in hours. Register locked after HR approval.",
      signatures: ["Prepared By", "Checked By", "Approved By"],
      generatedBy: user.name,
    });
  };

  const present = s.punches.filter((p) => p.date === dStr(0) || p.status === "Present").length;

  return (
    <div className="fade-up">
      <PageHead title="Attendance" crumbs={["Meridian", "People", "Attendance"]}
        desc="Web, GPS, QR and biometric punches — manager verification → HR approval → payroll. Corrections are controlled and audit-logged.">
        <Stat label="Marked today" value={`${s.attendance.length}`} />
        <Stat label="Pending approval" value={`${pending.length}`} tone={pending.length ? "warn" : "ok"} />
        <Stat label="OT hours (wk)" value={`${s.attendance.reduce((a, x) => a + x.ot, 0).toFixed(1)}`} />
        <Stat label="On leave" value={`${s.attendance.filter((a) => a.status === "On Leave").length}`} />
        <Btn onClick={printRegister}><IPrinter size={13} /> Print Register</Btn>
      </PageHead>

      <Widget title={tab === "today" ? "Today's Punches" : tab === "punches" ? "Attendance Records" : "Approval Queue"}
        subtitle={tab === "approvals" ? "Approvals flow to payroll once HR locks the register" : "Punch methods verified with GPS radius & device checks"}>
        <div className="mb-3"><Seg value={tab} onChange={setTab} options={[{ k: "today" as const, l: "Today", n: s.punches.length }, { k: "punches" as const, l: "Records", n: s.attendance.length }, { k: "approvals" as const, l: "Approvals", n: pending.length }]} /></div>

        {tab === "today" && (
          <div className="space-y-2">
            {s.punches.slice(0, 8).map((p) => (
              <div key={p.id} className="flex items-center gap-3 border border-line rounded-lg px-3.5 py-2.5 hover:border-line-strong transition-all">
                <span className="h-8 w-8 rounded-full grid place-items-center bg-brand-50 text-brand-700 border border-brand-100 shrink-0"><ICamera size={14} /></span>
                <div className="min-w-0 flex-1">
                  <p className="text-[12.5px] font-semibold text-ink-900">{p.user}</p>
                  <p className="text-[10.5px] text-ink-400 num">{p.method} · {p.project} · {p.date}</p>
                </div>
                <div className="text-right hidden sm:block">
                  <p className="num text-[11.5px] text-ink-500">In {p.inAt ?? "—"} · Out {p.outAt ?? "—"}</p>
                  {p.breakStart && <p className="num text-[10px] text-ink-300">Break {p.breakStart}{p.breakEnd ? `–${p.breakEnd}` : " (open)"}</p>}
                </div>
                <Pill value={p.status} pulse={p.status === "Late"} />
              </div>))}
            {s.punches.length === 0 && <p className="text-[12px] text-ink-400 py-4 text-center">No punches recorded yet today — use the punch widget in the header.</p>}
          </div>)}

        {tab === "punches" && <DataTable pageKey="att-rec" rows={s.attendance} cols={aCols.filter((c) => c.key !== "act")} />}
        {tab === "approvals" && <DataTable pageKey="att-appr" rows={pending} cols={aCols} empty={{ title: "Queue clear", note: "All attendance entries verified. New submissions land here for approval." }} />}
      </Widget>
    </div>
  );
}

/* ══════════ HR & PEOPLE ══════════ */
export function HRPage() {
  const { s, setS, can, log, notify, user } = useERP();
  const toast = useToast();
  const [tab, setTab] = useState<"emp" | "leave" | "punches">("emp");
  const [q, setQ] = useState("");
  const [view, setView] = useState<any>(null);

  const emps = s.employees.filter((e) => (e.id + e.name + e.dept + e.designation + e.project).toLowerCase().includes(q.toLowerCase()));
  const pendingLv = s.leaves.filter((l) => l.status === "Pending");

  const decideLeave = (l: any, ok: boolean) => {
    setS((p) => ({ ...p, leaves: p.leaves.map((x) => x.id === l.id ? { ...x, status: ok ? "Approved" : "Rejected" } : x) }));
    log("HR", ok ? "Leave Approved" : "Leave Rejected", l.emp, `${l.type} · ${l.days} day(s) · ${l.from} → ${l.to}`);
    notify("hr", `Leave ${ok ? "approved" : "rejected"} for ${l.emp}`);
    toast(ok ? "success" : "info", `Leave ${ok ? "approved" : "rejected"}`);
  };

  const eCols: Col[] = [
    { key: "id", label: "Employee", render: (e) => <div><p className="text-[12.5px] font-semibold text-ink-900">{e.name}</p><p className="text-[10.5px] num text-ink-400">{e.id}</p></div> },
    { key: "designation", label: "Designation", render: (e) => <span className="text-[12px] text-ink-700">{e.designation}</span> },
    { key: "dept", label: "Department", render: (e) => <span className="text-[12px] text-ink-500">{e.dept}</span> },
    { key: "project", label: "Project", render: (e) => <span className="num text-[12px] text-ink-500">{e.project}</span> },
    { key: "joined", label: "Joined", render: (e) => <span className="num text-[11.5px] text-ink-500">{e.joined}</span> },
    { key: "base", label: "CTC (₹ L/yr)", align: "right", sort: (e) => e.base, render: (e) => <span className="num text-[12.5px] font-semibold">{e.base.toFixed(2)}</span> },
    { key: "act", label: "", render: (e: any) => <Btn sm onClick={(ev: any) => { ev.stopPropagation(); setView(e); }}><IEye size={11} /> Profile</Btn> },
  ];

  return (
    <div className="fade-up">
      <PageHead title="HR & People" crumbs={["Meridian", "People"]}
        desc="Employee master, leave management and approvals — joined to attendance and payroll.">
        <Stat label="Employees" value={`${s.employees.length}`} />
        <Stat label="Pending leaves" value={`${pendingLv.length}`} tone={pendingLv.length ? "warn" : "ok"} />
        <Stat label="Departments" value={`${new Set(s.employees.map((e) => e.dept)).size}`} />
        <Stat label="Avg CTC" value={`₹${(s.employees.reduce((a, e) => a + e.base, 0) / s.employees.length).toFixed(2)} L`} />
      </PageHead>

      <Widget title={tab === "emp" ? "Employee Directory" : tab === "leave" ? "Leave Requests" : "Attendance Link"} subtitle="Self-service for employees; approvals for HR & managers">
        <div className="mb-3"><Seg value={tab} onChange={setTab} options={[{ k: "emp" as const, l: "Employees", n: s.employees.length }, { k: "leave" as const, l: "Leave", n: s.leaves.length }, { k: "punches" as const, l: "Attendance", n: s.attendance.length }]} /></div>

        {tab === "emp" && <>
          <FilterBar pageKey="hr-emp" q={q} onQ={setQ} filters={[]} />
          <DataTable pageKey="employees" rows={emps} cols={eCols} onRow={(e) => setView(e)} />
        </>}

        {tab === "leave" && (
          <DataTable pageKey="leaves" rows={s.leaves} cols={[
            { key: "emp", label: "Employee", render: (l) => <span className="text-[12.5px] font-semibold text-ink-900">{l.emp}</span> },
            { key: "type", label: "Type", render: (l) => <span className="text-[10.5px] font-bold uppercase bg-canvas border border-line rounded px-1.5 py-0.5 text-ink-500">{l.type}</span> },
            { key: "period", label: "Period", render: (l) => <span className="num text-[11.5px] text-ink-500">{l.from} → {l.to} · {l.days} d</span> },
            { key: "reason", label: "Reason", render: (l) => <span className="text-[11.5px] text-ink-500 truncate max-w-[220px] block">{l.reason}</span> },
            { key: "status", label: "Status", render: (l) => <Pill value={l.status} pulse={l.status === "Pending"} /> },
            { key: "act", label: "", render: (l: any) => l.status === "Pending" && can("hr", "approve") ? (
              <span className="flex gap-1 justify-end">
                <Btn sm kind="ok" onClick={(e: any) => { e.stopPropagation(); decideLeave(l, true); }}><ICheck size={11} /></Btn>
                <Btn sm kind="danger" onClick={(e: any) => { e.stopPropagation(); decideLeave(l, false); }}><IXCircle size={11} /></Btn>
              </span>) : null },
          ] as Col[]} />
        )}

        {tab === "punches" && (
          <div className="space-y-2">
            {s.attendance.map((a) => (
              <div key={a.id} className="flex items-center gap-3 border border-line rounded-lg px-3.5 py-2.5">
                <div className="min-w-0 flex-1">
                  <p className="text-[12.5px] font-semibold text-ink-900">{a.name}</p>
                  <p className="text-[10.5px] num text-ink-400">{a.empId} · {a.project}</p>
                </div>
                <span className="num text-[11.5px] text-ink-500">{a.hours || 0} hrs{a.ot ? ` + ${a.ot} OT` : ""}</span>
                <Pill value={a.status} /><Pill value={a.appr} />
              </div>))}
          </div>)}
      </Widget>

      <Drawer open={!!view} onClose={() => setView(null)} title={view?.name ?? ""} sub={view ? `${view.id} · ${view.designation}` : ""}>
        {view && (
          <div className="space-y-3">
            {[["Department", view.dept], ["Project", view.project], ["Joined", view.joined], ["CTC", `₹${view.base.toFixed(2)} L / yr`], ["Reports to", view.role === "PM" ? "Rajesh Malhotra" : "Project Manager"]].map(([k, v]) => (
              <div key={k} className="flex justify-between border-b border-line/70 pb-2 text-[12.5px]"><span className="text-ink-400 font-semibold">{k}</span><span className="text-ink-900 font-medium num">{v}</span></div>))}
            <div className="rounded-lg border border-line p-3.5">
              <p className="text-[10px] font-bold uppercase tracking-wide text-brand-700 mb-2">Documents on file</p>
              {["Appointment letter", "ID & address proof", "PF nomination", "Insurance policy"].map((d) => (
                <p key={d} className="flex items-center gap-1.5 text-[11.5px] text-ok-600 py-0.5"><ICheck size={11} /> {d}</p>))}
            </div>
          </div>)}
      </Drawer>
    </div>
  );
}

/* ══════════ PAYROLL ══════════ */
export function PayrollPage() {
  const { s, setS, can, log, notify, user } = useERP();
  const toast = useToast();
  const [slip, setSlip] = useState<any>(null);

  const advance = (r: any) => {
    const next = r.status === "Draft" ? "Processing" : r.status === "Processing" ? "Approved" : "Paid";
    setS((p) => ({ ...p, payRuns: p.payRuns.map((x) => x.id === r.id ? { ...x, status: next } : x) }));
    log("Payroll", `Run ${next}`, r.period, `${r.employees} employees · net ₹${r.net} Cr`);
    if (next === "Paid") notify("hr", `${r.period} payroll disbursed — ₹${r.net} Cr`);
    toast("success", `${r.period} → ${next}`);
  };

  const printSlip = (e: any) => {
    const basic = e.base * 1e5, hra = basic * 0.4, sp = basic * 0.15, gross = basic + hra + sp;
    const pf = basic * 0.12, pt = 2400, net = gross - pf - pt;
    printDocument({
      title: "Payslip", docNo: `SLIP-${e.id}-${dStr(0).slice(3).replace(/\s/g, "")}`, date: dStr(0),
      meta: [["Employee", `${e.name} (${e.id})`], ["Designation", e.designation], ["Department", e.dept], ["Project", e.project], ["Pay Period", dStr(0).slice(3)]],
      cols: [{ label: "Component" }, { label: "Amount (₹ / yr)", align: "right" }],
      rows: [["Basic", basic], ["HRA (40%)", hra], ["Special Allowance", sp], ["Gross", gross], ["Less: PF @12%", -pf], ["Less: Professional Tax", -pt], ["Net Payable", net]],
      totalsLabel: "Net Annual Pay", totals: [net],
      inWords: net,
      signatures: ["Prepared By", "Accounts Manager"],
      note: "Computer generated payslip. Earnings linked to approved attendance; deductions as per statutory rates.",
      generatedBy: user.name,
    });
  };

  return (
    <div className="fade-up">
      <PageHead title="Payroll" crumbs={["Meridian", "People", "Payroll"]}
        desc="Attendance-linked payroll runs with payslips. Draft → Processing → Approved → Paid.">
        <Stat label="Active run" value={s.payRuns.find((r) => r.status === "Processing")?.period ?? "—"} />
        <Stat label="Employees paid" value={`${s.payRuns.find((r) => r.status === "Paid")?.employees ?? 0}`} />
        <Stat label="Net disbursed" value={`₹${s.payRuns.filter((r) => r.status === "Paid").reduce((a, r) => a + r.net, 0).toFixed(2)} Cr`} tone="ok" />
      </PageHead>

      <Widget title="Payroll Runs" subtitle="Each run reconciles approved attendance, overtime and statutory deductions">
        <DataTable pageKey="payroll" rows={s.payRuns} cols={[
          { key: "period", label: "Period", render: (r) => <span className="text-[12.5px] font-bold text-ink-900">{r.period}</span> },
          { key: "employees", label: "Employees", align: "right", sort: (r) => r.employees, render: (r) => <span className="num text-[12.5px] font-semibold">{r.employees.toLocaleString("en-IN")}</span> },
          { key: "gross", label: "Gross (₹ Cr)", align: "right", sort: (r) => r.gross, render: (r) => <span className="num text-[12.5px]">{r.gross.toFixed(2)}</span> },
          { key: "deductions", label: "Deductions", align: "right", render: (r) => <span className="num text-[12px] text-danger-600">−{r.deductions.toFixed(2)}</span> },
          { key: "net", label: "Net (₹ Cr)", align: "right", sort: (r) => r.net, render: (r) => <span className="num text-[12.5px] font-bold text-ink-900">{r.net.toFixed(2)}</span> },
          { key: "date", label: "Date", render: (r) => <span className="num text-[11.5px] text-ink-500">{r.date}</span> },
          { key: "status", label: "Status", render: (r) => <Pill value={r.status === "Paid" ? "Completed" : r.status === "Approved" ? "On Track" : "Pending"} pulse={r.status === "Processing"} />, csv: (r) => r.status },
          { key: "act", label: "", render: (r: any) => r.status !== "Paid" && can("payroll", "approve") ? (
            <Btn sm kind="primary" onClick={(e: any) => { e.stopPropagation(); advance(r); }}>
              {r.status === "Draft" ? "Process" : r.status === "Processing" ? "Approve" : "Disburse"}</Btn>) : null },
        ] as Col[]} />
      </Widget>

      <Widget title="Payslips" subtitle="Generated from the employee master — click to preview, print a signed slip">
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-2">
          {s.employees.map((e) => (
            <button key={e.id} onClick={() => setSlip(e)} className="text-left rounded-lg border border-line bg-surface px-3.5 py-3 hover:border-brand-200 hover:bg-brand-50/30 hover:-translate-y-[2px] transition-all duration-200 active:scale-[0.98]">
              <p className="text-[12.5px] font-bold text-ink-900 truncate">{e.name}</p>
              <p className="text-[10.5px] num text-ink-400 mt-0.5">{e.id} · {e.designation}</p>
              <p className="num text-[12px] font-semibold text-brand-700 mt-1.5">₹{(e.base / 12).toFixed(2)} L / mo</p>
            </button>))}
        </div>
      </Widget>

      <Drawer open={!!slip} onClose={() => setSlip(null)} title={`Payslip — ${slip?.name}`} sub={slip ? `${slip.id} · ${slip.designation} · ${slip.dept}` : ""}>
        {slip && (() => {
          const basic = slip.base * 1e5, hra = basic * 0.4, sp = basic * 0.15, gross = basic + hra + sp;
          const pf = basic * 0.12, pt = 2400, net = gross - pf - pt;
          return (
            <div className="space-y-3">
              <div className="rounded-lg border border-line p-4 space-y-1.5">
                {[["Basic", basic], ["HRA (40%)", hra], ["Special Allowance", sp]].map(([k, v]) => (
                  <div key={k as string} className="flex justify-between text-[12.5px]"><span className="text-ink-500">{k}</span><span className="num font-semibold text-ink-900">₹{(v as number).toLocaleString("en-IN", { maximumFractionDigits: 0 })}</span></div>))}
                <div className="flex justify-between text-[12.5px] border-t border-line pt-2"><span className="font-bold text-ink-700">Gross</span><span className="num font-bold">₹{gross.toLocaleString("en-IN", { maximumFractionDigits: 0 })}</span></div>
                {[["PF @12%", pf], ["Professional Tax", pt]].map(([k, v]) => (
                  <div key={k as string} className="flex justify-between text-[12.5px]"><span className="text-ink-500">{k}</span><span className="num text-danger-600">−₹{(v as number).toLocaleString("en-IN", { maximumFractionDigits: 0 })}</span></div>))}
                <div className="flex justify-between items-center border-t-2 border-line-strong pt-2.5 mt-1"><span className="text-[11px] font-extrabold uppercase tracking-wide text-brand-700">Net Annual</span><span className="num text-[19px] font-bold text-ink-900">₹{net.toLocaleString("en-IN", { maximumFractionDigits: 0 })}</span></div>
              </div>
              <div className="flex justify-end"><Btn kind="primary" onClick={() => printSlip(slip)}><IPrinter size={13} /> Print Payslip</Btn></div>
            </div>);
        })()}
      </Drawer>
    </div>
  );
}
