/* Part 2 · People Ops, Quality, Safety, Plant Ops, Vendors, Audit — one shared ledger */
import { useMemo, useState } from "react";
import { useERP, dStr } from "../store";
import { VENDORS } from "../data";
import { Widget, Pill, Bar, cx, useToast, Empty } from "../ui";
import { PageHead, Seg, FilterBar, DataTable, Drawer, Field, inputCls, selectCls, Btn, Stat, exportCSV } from "./core";
import type { Col } from "./core";
import { printDocument } from "../print";
import { ICheck, IXCircle, IPrinter, IDownload, IAlert, IFlask, IShield, ICrane, IClock } from "../icons";

const INR = (v: number) => "₹" + v.toLocaleString("en-IN", { maximumFractionDigits: 0 });

/* ══════════ PF MANAGEMENT ══════════ */
export function PFPage() {
  const { s, setS, can, log, notify, user } = useERP();
  const toast = useToast();
  const pending = s.pf.filter((p) => p.status === "Pending");
  const total = s.pf.reduce((a, p) => a + p.empShare + p.erShare, 0);

  const pay = (p: any) => {
    setS((st) => ({ ...st, pf: st.pf.map((x) => x.id === p.id ? { ...x, status: "Paid", paidOn: dStr(0) } : x) }));
    log("Payroll", "PF Remitted", p.pfNo, `${p.emp} · ${p.month} · ${INR(p.empShare + p.erShare)}`);
    notify("hr", `PF remitted for ${p.emp} — ${p.month}`);
    toast("success", `PF remitted — ${p.emp}`);
  };

  const printPF = () => printDocument({
    title: "Monthly PF Register", docNo: "PF-" + dStr(0).replace(/\s/g, ""), date: dStr(0),
    meta: [["Period", s.pf[0]?.month ?? "Current"], ["Establishment", "SAHAA INFRA LTD — MHAPP"], ["Generated By", user.name]],
    cols: [{ label: "Employee" }, { label: "PF No." }, { label: "Month" }, { label: "PF Wage (₹)", align: "right" }, { label: "Employee Share", align: "right" }, { label: "Employer Share", align: "right" }, { label: "Status" }],
    rows: s.pf.map((p) => [p.emp, p.pfNo, p.month, p.wage, p.empShare, p.erShare, p.status]),
    totalsLabel: "Total Contribution (₹)", totals: [total],
    signatures: ["Prepared By", "Accounts Manager"],
    note: "Employee 12% + Employer 12% on PF wage, capped as per EPF Act. Sensitive wage details restricted to HR & Accounts.",
    generatedBy: user.name,
  });

  return (
    <div className="fade-up">
      <PageHead title="PF Management" crumbs={["Meridian", "People", "Provident Fund"]}
        desc="EPF contributions linked to payroll — wage, employee & employer share, remittance tracking.">
        <Stat label="Total contribution" value={INR(total)} />
        <Stat label="Pending remittance" value={`${pending.length}`} tone={pending.length ? "warn" : "ok"} />
        <Stat label="Rate" value="12% + 12%" sub="Employee + Employer" />
        <Btn onClick={printPF}><IPrinter size={13} /> Print Register</Btn>
      </PageHead>
      <Widget title="PF Register" subtitle="Remittance posts a Payment voucher to Accounts on approval">
        <DataTable pageKey="pf" rows={s.pf} cols={[
          { key: "emp", label: "Employee", render: (p) => <span className="text-[12.5px] font-semibold text-ink-900">{p.emp}</span> },
          { key: "pfNo", label: "PF No.", render: (p) => <span className="num text-[11.5px] text-ink-500">{p.pfNo}</span> },
          { key: "month", label: "Month", render: (p) => <span className="text-[12px] text-ink-500">{p.month}</span> },
          { key: "wage", label: "PF Wage", align: "right", sort: (p) => p.wage, render: (p) => <span className="num text-[12px]">{INR(p.wage)}</span> },
          { key: "empShare", label: "Employee", align: "right", sort: (p) => p.empShare, render: (p) => <span className="num text-[12px]">{INR(p.empShare)}</span> },
          { key: "erShare", label: "Employer", align: "right", sort: (p) => p.erShare, render: (p) => <span className="num text-[12px]">{INR(p.erShare)}</span> },
          { key: "status", label: "Status", render: (p) => <Pill value={p.status === "Paid" ? "Completed" : "Pending"} pulse={p.status === "Pending"} />, csv: (p) => p.status },
          { key: "act", label: "", render: (p: any) => p.status === "Pending" && can("payroll", "approve") ? <Btn sm kind="ok" onClick={(e: any) => { e.stopPropagation(); pay(p); }}><ICheck size={11} /> Remit</Btn> : null },
        ] as Col[]} />
      </Widget>
    </div>
  );
}

/* ══════════ PEOPLE OPS — corrections · salary history · assignments · exits ══════════ */
export function PeopleOpsPage() {
  const { s, setS, can, log, notify, user } = useERP();
  const toast = useToast();
  const [tab, setTab] = useState<"corr" | "sal" | "asg" | "exit">("corr");

  const decideCorr = (c: any, ok: boolean) => {
    setS((p) => ({ ...p, corrections: p.corrections.map((x) => x.id === c.id ? { ...x, status: ok ? "Approved" : "Rejected" } : x) }));
    log("Attendance", ok ? "Correction Approved" : "Correction Rejected", c.emp, `${c.date} · ${c.existing} → ${c.requested}`);
    notify("hr", `Attendance correction ${ok ? "approved" : "rejected"} for ${c.emp}`);
    toast(ok ? "success" : "info", `Correction ${ok ? "approved" : "rejected"}`);
  };

  return (
    <div className="fade-up">
      <PageHead title="People Operations" crumbs={["Meridian", "People", "Operations"]}
        desc="Attendance corrections, salary history, project assignments and exits — historical records are never overwritten.">
        <Stat label="Open corrections" value={`${s.corrections.filter((c) => c.status === "Pending").length}`} tone="warn" />
        <Stat label="Active assignments" value={`${s.assignments.filter((a) => a.status === "Active").length}`} />
        <Stat label="Exits (FY)" value={`${s.exits.length}`} />
      </PageHead>
      <Widget title={tab === "corr" ? "Attendance Corrections" : tab === "sal" ? "Salary History" : tab === "asg" ? "Project Assignments" : "Exit / Full & Final"}
        subtitle={tab === "corr" ? "Employee → Reporting Manager → HR · full history retained" : tab === "sal" ? "Revisions are appended, never overwritten" : tab === "asg" ? "Chronological assignment trail per employee" : "Notice → LWD → F&F → approval → exit"}>
        <div className="mb-3"><Seg value={tab} onChange={setTab} options={[
          { k: "corr" as const, l: "Corrections", n: s.corrections.length }, { k: "sal" as const, l: "Salary History", n: s.salaryHist.length },
          { k: "asg" as const, l: "Assignments", n: s.assignments.length }, { k: "exit" as const, l: "Exits", n: s.exits.length },
        ]} /></div>

        {tab === "corr" && (
          <DataTable pageKey="corr" rows={s.corrections} cols={[
            { key: "emp", label: "Employee", render: (c) => <span className="text-[12.5px] font-semibold text-ink-900">{c.emp}</span> },
            { key: "date", label: "Date", render: (c) => <span className="num text-[11.5px] text-ink-500">{c.date}</span> },
            { key: "existing", label: "Existing Record", render: (c) => <span className="text-[12px] text-danger-600 line-through decoration-danger-500/50">{c.existing}</span> },
            { key: "requested", label: "Requested", render: (c) => <span className="text-[12px] font-semibold text-ok-600">{c.requested}</span> },
            { key: "reason", label: "Reason", render: (c) => <span className="text-[11.5px] text-ink-500 truncate max-w-[240px] block">{c.reason}</span> },
            { key: "status", label: "Status", render: (c) => <Pill value={c.status} pulse={c.status === "Pending"} /> },
            { key: "act", label: "", render: (c: any) => c.status === "Pending" && can("hr", "approve") ? (
              <span className="flex gap-1 justify-end">
                <Btn sm kind="ok" onClick={(e: any) => { e.stopPropagation(); decideCorr(c, true); }}><ICheck size={11} /></Btn>
                <Btn sm kind="danger" onClick={(e: any) => { e.stopPropagation(); decideCorr(c, false); }}><IXCircle size={11} /></Btn>
              </span>) : null },
          ] as Col[]} />
        )}

        {tab === "sal" && (
          <DataTable pageKey="salhist" rows={s.salaryHist} cols={[
            { key: "emp", label: "Employee", render: (h) => <span className="text-[12.5px] font-semibold text-ink-900">{h.emp}</span> },
            { key: "effective", label: "Effective", render: (h) => <span className="num text-[11.5px] text-ink-500">{h.effective}</span> },
            { key: "basic", label: "Basic", align: "right", sort: (h) => h.basic, render: (h) => <span className="num text-[12px]">{INR(h.basic)}</span> },
            { key: "allowances", label: "Allowances", align: "right", render: (h) => <span className="num text-[12px]">{INR(h.allowances)}</span> },
            { key: "gross", label: "Gross", align: "right", sort: (h) => h.gross, render: (h) => <span className="num text-[12.5px] font-semibold">{INR(h.gross)}</span> },
            { key: "net", label: "Net", align: "right", sort: (h) => h.net, render: (h) => <span className="num text-[12.5px] font-semibold text-ink-900">{INR(h.net)}</span> },
            { key: "reason", label: "Revision Reason", render: (h) => <span className="text-[11.5px] text-ink-500">{h.reason}</span> },
            { key: "by", label: "Approved By", render: (h) => <span className="text-[11.5px] text-ink-500">{h.by}</span> },
          ] as Col[]} />
        )}

        {tab === "asg" && (
          <DataTable pageKey="asg" rows={s.assignments} cols={[
            { key: "user", label: "Employee", render: (a) => <div><p className="text-[12.5px] font-semibold text-ink-900">{a.user}</p><p className="text-[10px] num text-ink-400">{a.site} · reports to {a.manager}</p></div> },
            { key: "project", label: "Project", render: (a) => <span className="num text-[12px] text-brand-700 font-semibold">{a.project}</span> },
            { key: "role", label: "Role on Project", render: (a) => <div><p className="text-[12px] text-ink-700">{a.role}</p><p className="text-[10px] text-ink-400 max-w-[240px] truncate">{a.responsibility}</p></div> },
            { key: "finLimit", label: "Fin. Limit", render: (a) => <span className="num text-[11.5px] text-ink-700 font-semibold">{a.finLimit}</span> },
            { key: "from", label: "From", render: (a) => <span className="num text-[11.5px] text-ink-500">{a.from}</span> },
            { key: "to", label: "To", render: (a) => <span className="num text-[11.5px] text-ink-500">{a.to === "—" ? "Current" : a.to}</span> },
            { key: "status", label: "Status", render: (a) => <Pill value={a.status === "Active" ? "On Track" : "Completed"} />, csv: (a) => a.status },
          ] as Col[]} />
        )}

        {tab === "exit" && (
          <DataTable pageKey="exits" rows={s.exits} cols={[
            { key: "emp", label: "Employee", render: (x) => <span className="text-[12.5px] font-semibold text-ink-900">{x.emp}</span> },
            { key: "lastDay", label: "Last Working Day", render: (x) => <span className="num text-[11.5px] text-ink-500">{x.lastDay}</span> },
            { key: "reason", label: "Exit Reason", render: (x) => <span className="text-[12px] text-ink-500">{x.reason}</span> },
            { key: "fnf", label: "F&F Amount (₹ L)", align: "right", sort: (x) => x.fnf, render: (x) => <span className="num text-[12.5px] font-semibold">{x.fnf.toFixed(2)}</span> },
            { key: "status", label: "Status", render: (x) => <Pill value={x.status === "Completed" ? "Completed" : "Pending"} pulse={x.status === "In Progress"} />, csv: (x) => x.status },
          ] as Col[]} />
        )}
      </Widget>
    </div>
  );
}

/* ══════════ QUALITY ══════════ */
export function QualityPage() {
  const { s, setS, can, log, notify, user } = useERP();
  const toast = useToast();
  const [tab, setTab] = useState<"all" | "Inspection" | "NCR" | "Cube Test">("all");

  const rows = s.quality.filter((q) => tab === "all" || q.type === tab);
  const failed = s.quality.filter((q) => q.status === "Failed" || (q.type === "NCR" && q.status === "Open"));

  const advance = (q: any) => {
    const next = q.status === "Pending" ? "Passed" : q.status === "Open" ? "Closed" : q.status;
    setS((p) => ({ ...p, quality: p.quality.map((x) => x.id === q.id ? { ...x, status: next } : x) }));
    log("Quality", q.type + " " + next, q.no, `${q.item}`);
    notify("system", `${q.no} marked ${next}`);
    toast("success", `${q.no} → ${next}`);
  };

  return (
    <div className="fade-up">
      <PageHead title="Quality Management" crumbs={["Meridian", "Site Operations", "Quality"]}
        desc="Inspections, NCRs and cube tests with corrective-action tracking. Failed tests raise alerts automatically.">
        <Stat label="Inspections" value={`${s.quality.filter((q) => q.type === "Inspection").length}`} />
        <Stat label="Open NCRs" value={`${s.quality.filter((q) => q.type === "NCR" && q.status === "Open").length}`} tone="warn" />
        <Stat label="Cube pass rate" value={`${Math.round((s.quality.filter((q) => q.type === "Cube Test" && q.status === "Passed").length / Math.max(1, s.quality.filter((q) => q.type === "Cube Test").length)) * 100)}%`} tone="ok" />
        <Stat label="Failed / open" value={`${failed.length}`} tone={failed.length ? "danger" : "ok"} />
      </PageHead>
      <Widget title="Quality Records" subtitle="Failed cube tests trigger mix-design review; NCRs require root cause before closure">
        <div className="mb-3"><Seg value={tab} onChange={setTab} options={[
          { k: "all" as const, l: "All", n: s.quality.length }, { k: "Inspection" as const, l: "Inspections" },
          { k: "NCR" as const, l: "NCR" }, { k: "Cube Test" as const, l: "Cube Tests" },
        ]} /></div>
        <div className="grid lg:grid-cols-2 gap-3">
          {rows.map((q) => (
            <div key={q.id} className={cx("rounded-lg border p-3.5 transition-all hover:-translate-y-[2px] hover:shadow-lift", q.status === "Failed" || (q.type === "NCR" && q.status === "Open") ? "border-danger-500/30 bg-danger-100/20" : "border-line bg-surface")}>
              <div className="flex items-center gap-2 flex-wrap">
                <span className="num text-[12px] font-bold text-brand-700">{q.no}</span>
                <span className="text-[10px] font-bold uppercase tracking-wide bg-canvas border border-line rounded px-1.5 py-0.5 text-ink-500 flex items-center gap-1"><IFlask size={10} /> {q.type}</span>
                <span className="num text-[11px] text-ink-400">{q.project} · {q.date}</span>
                <span className="ml-auto"><Pill value={q.status} pulse={q.status === "Pending" || q.status === "Open"} /></span>
              </div>
              <p className="text-[12.5px] font-semibold text-ink-900 mt-2">{q.item}</p>
              {q.result && <p className="text-[11.5px] text-ink-500 mt-1">{q.result}</p>}
              {(q.status === "Pending" || q.status === "Open") && can("rmc", "edit") || (q.status === "Pending" && can("projects", "edit")) ? (
                <div className="flex justify-end mt-2.5">
                  <Btn sm kind={q.type === "NCR" ? "danger" : "ok"} onClick={() => advance(q)}>
                    {q.type === "NCR" ? "Close with Action" : "Mark Passed"}</Btn>
                </div>) : null}
            </div>))}
        </div>
        {rows.length === 0 && <Empty title="No records in this view" note="Quality records are created from site inspections and RMC batches." />}
      </Widget>
    </div>
  );
}

/* ══════════ SAFETY ══════════ */
export function SafetyPage() {
  const { s, setS, can, log, notify } = useERP();
  const toast = useToast();
  const close = (x: any) => {
    setS((p) => ({ ...p, safety: p.safety.map((y) => y.id === x.id ? { ...y, status: "Closed" } : y) }));
    log("Safety", x.kind + " Closed", x.project, x.desc);
    notify("system", `Safety item closed — ${x.kind}`);
    toast("success", "Item closed");
  };
  const tone: Record<string, string> = { "High": "bg-danger-100 text-danger-600", "Medium": "bg-amber-100 text-amber-600", "Low": "bg-steel-100 text-steel-600", "—": "bg-ok-100 text-ok-600" };
  return (
    <div className="fade-up">
      <PageHead title="Safety Management" crumbs={["Meridian", "Site Operations", "Safety"]}
        desc="Observations, incidents, near misses and toolbox talks with corrective-action closure.">
        <Stat label="Toolbox talks (wk)" value={`${s.safety.filter((x) => x.kind === "Toolbox Talk").length}`} tone="ok" />
        <Stat label="Open items" value={`${s.safety.filter((x) => x.status === "Open").length}`} tone="warn" />
        <Stat label="Incidents (FY)" value={`${s.safety.filter((x) => x.kind === "Incident").length}`} tone="danger" />
        <Stat label="Lost-time injuries" value="0" tone="ok" />
      </PageHead>
      <Widget title="Safety Log" subtitle="Every item records severity, action and closure">
        <div className="space-y-2">
          {s.safety.map((x) => (
            <div key={x.id} className="flex items-center gap-3 border border-line rounded-lg px-3.5 py-3 hover:border-line-strong transition-all">
              <span className={cx("h-8 w-8 rounded-md grid place-items-center shrink-0", tone[x.severity] ?? "bg-steel-100 text-steel-600")}><IShield size={15} /></span>
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2 flex-wrap">
                  <span className="text-[12.5px] font-semibold text-ink-900">{x.kind}</span>
                  <span className="num text-[11px] text-ink-400">{x.project} · {x.date}</span>
                  <span className={cx("text-[9.5px] font-bold uppercase tracking-wide px-1.5 py-0.5 rounded", tone[x.severity] ?? "bg-steel-100 text-steel-600")}>{x.severity}</span>
                </div>
                <p className="text-[12px] text-ink-500 mt-0.5">{x.desc}</p>
              </div>
              <Pill value={x.status === "Closed" || x.status === "Completed" ? "Completed" : "Pending"} pulse={x.status === "Open"} />
              {x.status === "Open" && can("projects", "edit") && <Btn sm onClick={() => close(x)}>Close</Btn>}
            </div>))}
        </div>
      </Widget>
    </div>
  );
}

/* ══════════ PLANT OPS — fleet · fuel · maintenance · utilization ══════════ */
export function PlantOpsPage() {
  const { s, setS, can, log, notify, user } = useERP();
  const toast = useToast();
  const [tab, setTab] = useState<"fleet" | "fuel" | "maint" | "util">("fleet");

  const eqName = (code: string) => s.equipment.find((e) => e.code === code)?.name ?? code;
  const utilOf = (code: string) => {
    const f = s.fuel.filter((x) => x.eq === code);
    const hrs = f.reduce((a, x) => a + x.hrs, 0);
    return Math.min(100, Math.round((hrs / 8) * 100));
  };

  const serve = (m: any) => {
    setS((p) => ({ ...p, maint: p.maint.map((x) => x.id === m.id ? { ...x, status: "Completed" } : x), equipment: p.equipment.map((e) => e.code === m.eq ? { ...e, status: "Operational", maintDue: dStr(45) } : e) }));
    log("Plant", "Maintenance Completed", m.eq, `${m.service} · cost ₹${m.cost} L → project cost`);
    notify("system", `${eqName(m.eq)} back in service after ${m.service}`);
    toast("success", `${m.service} completed`);
  };

  return (
    <div className="fade-up">
      <PageHead title="Plant & Machinery Operations" crumbs={["Meridian", "Site Operations", "Plant"]}
        desc="Fleet, fuel, maintenance and utilization — costs trace to projects via running hours.">
        <Stat label="Fleet" value={`${s.equipment.length}`} />
        <Stat label="Operational" value={`${s.equipment.filter((e) => e.status === "Operational").length}`} tone="ok" />
        <Stat label="Under maintenance" value={`${s.equipment.filter((e) => e.status === "Under Maintenance").length}`} tone="warn" />
        <Stat label="Overdue service" value={`${s.maint.filter((m) => m.status === "Overdue").length}`} tone="danger" />
        <Stat label="Fuel (3 d)" value={`${s.fuel.reduce((a, f) => a + f.ltrs, 0)} L`} />
      </PageHead>
      <Widget title={tab === "fleet" ? "Equipment Fleet" : tab === "fuel" ? "Fuel Register" : tab === "maint" ? "Maintenance" : "Utilization"}
        subtitle="Utilization = productive hours ÷ available hours · abnormal fuel flagged automatically">
        <div className="mb-3"><Seg value={tab} onChange={setTab} options={[
          { k: "fleet" as const, l: "Fleet", n: s.equipment.length }, { k: "fuel" as const, l: "Fuel", n: s.fuel.length },
          { k: "maint" as const, l: "Maintenance", n: s.maint.length }, { k: "util" as const, l: "Utilization" },
        ]} /></div>

        {tab === "fleet" && (
          <DataTable pageKey="fleet" rows={s.equipment} cols={[
            { key: "code", label: "Equipment", render: (e) => <div><p className="text-[12.5px] font-semibold text-ink-900">{e.name}</p><p className="text-[10.5px] num text-ink-400">{e.code} · {e.reg}</p></div> },
            { key: "cap", label: "Capacity", render: (e) => <span className="num text-[11.5px] text-ink-500">{e.cap}</span> },
            { key: "project", label: "Project", render: (e) => <span className="num text-[12px] text-brand-700 font-semibold">{e.project}</span> },
            { key: "hrs", label: "Hour Meter", align: "right", sort: (e) => e.hrs, render: (e) => <span className="num text-[12px] font-semibold">{e.hrs.toLocaleString("en-IN")} h</span> },
            { key: "maintDue", label: "Service Due", render: (e) => <span className="num text-[11.5px] text-ink-500">{e.maintDue}</span> },
            { key: "status", label: "Status", render: (e) => <Pill value={e.status === "Operational" ? "Active" : "Under Approval"} pulse={e.status === "Under Maintenance"} />, csv: (e) => e.status },
          ] as Col[]} />
        )}

        {tab === "fuel" && (
          <DataTable pageKey="fuel" rows={s.fuel} cols={[
            { key: "eq", label: "Equipment", render: (f) => <span className="text-[12.5px] font-semibold text-ink-900">{eqName(f.eq)}</span> },
            { key: "date", label: "Date", render: (f) => <span className="num text-[11.5px] text-ink-500">{f.date}</span> },
            { key: "type", label: "Fuel", render: (f) => <span className="text-[11.5px] text-ink-500">{f.type}</span> },
            { key: "ltrs", label: "Litres", align: "right", sort: (f) => f.ltrs, render: (f) => <span className="num text-[12px] font-semibold">{f.ltrs} L</span> },
            { key: "hrs", label: "Hours", align: "right", render: (f) => <span className="num text-[12px]">{f.hrs} h</span> },
            { key: "lph", label: "L / hr", align: "right", sort: (f) => f.hrs ? f.ltrs / f.hrs : 0, render: (f) => { const v = f.hrs ? f.ltrs / f.hrs : 0; return <span className={cx("num text-[12px] font-semibold", v > 6 ? "text-danger-600" : "text-ink-700")}>{v.toFixed(1)}</span>; } },
            { key: "cost", label: "Cost (₹)", align: "right", sort: (f) => f.cost, render: (f) => <span className="num text-[12px]">{INR(f.cost)}</span> },
          ] as Col[]} />
        )}

        {tab === "maint" && (
          <DataTable pageKey="maint" rows={s.maint} cols={[
            { key: "eq", label: "Equipment", render: (m) => <span className="text-[12.5px] font-semibold text-ink-900">{eqName(m.eq)}</span> },
            { key: "service", label: "Service", render: (m) => <span className="text-[12px] text-ink-700">{m.service}</span> },
            { key: "due", label: "Due", render: (m) => <span className={cx("num text-[11.5px]", m.status === "Overdue" ? "text-danger-600 font-semibold" : "text-ink-500")}>{m.due}</span> },
            { key: "cost", label: "Cost (₹ L)", align: "right", sort: (m) => m.cost, render: (m) => <span className="num text-[12px]">{m.cost.toFixed(1)}</span> },
            { key: "status", label: "Status", render: (m) => <Pill value={m.status === "Overdue" ? "Overdue" : m.status === "Completed" ? "Completed" : "Pending"} pulse={m.status === "Overdue"} /> },
            { key: "act", label: "", render: (m: any) => m.status !== "Completed" && can("plant", "edit") ? <Btn sm kind="ok" onClick={(e: any) => { e.stopPropagation(); serve(m); }}><ICheck size={11} /> Complete</Btn> : null },
          ] as Col[]} />
        )}

        {tab === "util" && (
          <div className="space-y-3.5">
            {s.equipment.map((e) => {
              const u = utilOf(e.code);
              const fuel = s.fuel.filter((f) => f.eq === e.code);
              const cost = fuel.reduce((a, f) => a + f.cost, 0) + (s.maint.find((m) => m.eq === e.code)?.cost ?? 0) * 1e5;
              return (
                <div key={e.code} className="border border-line rounded-lg px-4 py-3">
                  <div className="flex items-center gap-3 flex-wrap">
                    <div className="min-w-0 flex-1">
                      <p className="text-[12.5px] font-semibold text-ink-900">{e.name}</p>
                      <p className="text-[10.5px] num text-ink-400">{e.code} · {e.project} · {e.hrs.toLocaleString("en-IN")} hr meter</p>
                    </div>
                    <div className="w-[180px]"><Bar value={u} warn={u < 40} h={6} />
                      <p className="text-[10px] num text-ink-400 mt-1 text-right">{u}% of available hours</p></div>
                    <span className="num text-[12px] font-semibold text-ink-900 w-[110px] text-right">{INR(cost)} <span className="text-[9.5px] text-ink-400 font-normal block">cost → {e.project}</span></span>
                  </div>
                </div>);
            })}
          </div>)}
      </Widget>
    </div>
  );
}

/* ══════════ VENDORS ══════════ */
export function VendorsPage() {
  const { s } = useERP();
  const [q, setQ] = useState("");
  const poByVendor = (name: string) => s.proc.filter((d) => d.type === "PO" && d.party.toLowerCase().includes(name.split(" ")[0].toLowerCase()));
  const rows = VENDORS.filter((v) => (v.name + v.cat).toLowerCase().includes(q.toLowerCase()));
  return (
    <div className="fade-up">
      <PageHead title="Vendors" crumbs={["Meridian", "Supply Chain", "Vendors"]}
        desc="Approved vendor list with performance rating, open POs and payment position.">
        <Stat label="Approved vendors" value={`${VENDORS.length}`} />
        <Stat label="Avg on-time" value={`${Math.round(VENDORS.reduce((a, v) => a + v.onTime, 0) / VENDORS.length)}%`} tone="ok" />
        <Stat label="Open POs" value={`${s.proc.filter((d) => d.type === "PO" && !["Closed"].includes(d.status)).length}`} />
      </PageHead>
      <Widget title="Vendor Master & Performance" subtitle="Rating drives RFQ shortlisting in the procurement chain">
        <FilterBar pageKey="vendors" q={q} onQ={setQ} filters={[]} />
        <DataTable pageKey="vendors" rows={rows} cols={[
          { key: "name", label: "Vendor", render: (v) => <div><p className="text-[12.5px] font-semibold text-ink-900">{v.name}</p><p className="text-[10.5px] text-ink-400">GSTIN on file · {v.cat}</p></div> },
          { key: "cat", label: "Category", render: (v) => <span className="text-[10.5px] font-bold uppercase bg-canvas border border-line rounded px-1.5 py-0.5 text-ink-500">{v.cat}</span> },
          { key: "pos", label: "Open POs", align: "right", sort: (v) => v.pos, render: (v) => <span className="num text-[12.5px] font-semibold">{v.pos}</span> },
          { key: "onTime", label: "On-time Delivery", render: (v) => <div className="flex items-center gap-2"><div className="flex-1 max-w-[140px]"><Bar value={v.onTime} warn={v.onTime < 85} h={5} /></div><span className="num text-[11px] font-semibold w-9">{v.onTime}%</span></div> },
          { key: "rating", label: "Rating", align: "right", sort: (v) => v.rating, render: (v) => <span className="num text-[12.5px] font-bold text-amber-600">{v.rating.toFixed(1)} ★</span> },
        ] as Col[]} />
      </Widget>
    </div>
  );
}

/* ══════════ AUDIT LOGS ══════════ */
export function AuditPage() {
  const { s } = useERP();
  const [q, setQ] = useState("");
  const [fMod, setFMod] = useState("");
  const mods = [...new Set(s.audit.map((a) => a.module))];
  const rows = s.audit.filter((a) => (a.user + a.action + a.entity + a.module + a.detail).toLowerCase().includes(q.toLowerCase()) && (!fMod || a.module === fMod));
  return (
    <div className="fade-up">
      <PageHead title="Audit Trail" crumbs={["Meridian", "Control", "Audit"]}
        desc="Immutable record of every create, edit, submit, approval, sign, print and export. Nothing is silently deleted.">
        <Stat label="Records" value={`${s.audit.length}`} />
        <Stat label="Modules covered" value={`${mods.length}`} />
        <Stat label="Retention" value="7 yrs" sub="append-only" />
        <Btn onClick={() => {
          const head = ["Ref", "Time", "User", "Role", "Module", "Action", "Entity", "Detail", "IP"];
          const lines = rows.map((a) => [a.id, a.ts, a.user, a.role, a.module, a.action, a.entity, `"${a.detail}"`, a.ip].join(","));
          const blob = new Blob([[head.join(","), ...lines].join("\n")], { type: "text/csv" });
          const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = "audit-trail.csv"; a.click();
        }}><IDownload size={13} /> Export</Btn>
      </PageHead>
      <Widget title="Audit Log" subtitle="Records cannot be edited or deleted by any user">
        <FilterBar pageKey="audit" q={q} onQ={setQ} filters={[{ key: "module", label: "Module", value: fMod, options: mods, onChange: setFMod }]} />
        <DataTable pageKey="auditlog" rows={rows} pageSize={10} cols={[
          { key: "id", label: "Ref", render: (a) => <span className="num text-[11px] font-bold text-brand-700">{a.id}</span> },
          { key: "ts", label: "Timestamp", render: (a) => <span className="num text-[10.5px] text-ink-500 whitespace-nowrap">{new Date(a.ts).toLocaleString("en-IN", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" })}</span> },
          { key: "user", label: "User", render: (a) => <div><p className="text-[12px] font-semibold text-ink-900">{a.user}</p><p className="text-[10px] text-ink-400">{a.role}</p></div> },
          { key: "module", label: "Module", render: (a) => <span className="text-[10.5px] font-bold uppercase bg-canvas border border-line rounded px-1.5 py-0.5 text-ink-500">{a.module}</span> },
          { key: "action", label: "Action", render: (a) => <span className="text-[12px] font-semibold text-ink-700">{a.action}</span> },
          { key: "entity", label: "Entity", render: (a) => <span className="num text-[11.5px] text-ink-500">{a.entity}</span> },
          { key: "detail", label: "Detail", render: (a) => <span className="text-[11.5px] text-ink-500">{a.detail}</span> },
          { key: "ip", label: "IP", render: (a) => <span className="num text-[10.5px] text-ink-300">{a.ip}</span> },
        ] as Col[]} />
      </Widget>
    </div>
  );
}
