/**
 * Part 14 — Procurement Types
 * Type definitions for indent, RFQ, quotation, comparative, PO, and rate contracts
 */

// ─── Indent (Purchase Requisition) ───────────────────────────────────────────

export type IndentType = 'REGULAR' | 'URGENT' | 'EMERGENCY' | 'STOCK_REPLENISH' | 'CAPEX';
export type BudgetStatus = 'WITHIN' | 'EXCEEDED' | 'NO_BUDGET' | 'OVERRIDDEN';
export type IndentStatus = 'DRAFT' | 'PENDING_APPROVAL' | 'APPROVED' | 'REJECTED' | 'CANCELLED' | 'CONVERTED_TO_RFQ';

export interface IndentExtension {
  indentId: number;
  projectId: number;
  wbsId?: number;
  costCodeId?: number;
  indentType: IndentType;
  requiredByDate: string;
  justification?: string;
  budgetCheckedAt?: string;
  budgetStatus?: BudgetStatus;
  budgetAvailable?: number;
  stockCheckedAt?: string;
  sourcePlanId?: number; // dx_resource_plan row
  consolidationGroup?: string;
  isAutoGenerated: boolean;
}

export interface IndentItemExtension {
  indentItemId: number;
  itemId?: number;
  boqItemId?: number;
  wbsId?: number;
  specification?: string;
  makePreference?: string;
  stockOnHand: number;
  stockInTransit: number;
  alreadyOrdered: number;
  theoreticalReq: number; // from Part 13 norms
  netRequired: number;
  lastPurchaseRate?: number;
  lastPurchaseDate?: string;
  budgetRate?: number;
  estimatedValue?: number;
}

export interface IndentCheck {
  checkType: 'STOCK' | 'THEORETICAL' | 'BUDGET' | 'DUPLICATE' | 'LEAD_TIME';
  status: 'PASS' | 'WARN' | 'FAIL';
  message: string;
  details?: any;
}

export interface IndentValidation {
  isValid: boolean;
  checks: IndentCheck[];
  canSubmit: boolean;
  requiresOverride: boolean;
  overrideReason?: string;
}

// ─── RFQ (Request for Quotation) ─────────────────────────────────────────────

export type RfqType = 'OPEN' | 'LIMITED' | 'SINGLE' | 'RATE_CONTRACT';
export type RfqStatus = 'DRAFT' | 'ISSUED' | 'CLOSED' | 'SEALED' | 'OPENED' | 'CANCELLED' | 'AWARDED';
export type VendorResponseStatus = 'INVITED' | 'VIEWED' | 'QUOTED' | 'REGRETTED' | 'NO_RESPONSE';

export interface Rfq {
  id: number;
  rfqNo: string;
  projectId?: number;
  companyId: number;
  rfqType: RfqType;
  title: string;
  scopeSummary?: string;
  issueDate: string;
  dueDatetime: string;
  isSealed: boolean;
  openedAt?: string;
  openedBy?: number[]; // Two users for sealed RFQ
  status: RfqStatus;
  deliveryTerms?: string;
  paymentTerms?: string;
  createdBy: number;
  createdAt: string;
  indentMappings?: RfqIndentMap[];
  vendors?: RfqVendor[];
  quotations?: Quotation[];
  comparative?: Comparative;
}

export interface RfqIndentMap {
  id: number;
  rfqId: number;
  indentItemId: number;
  rfqQty: number;
}

export interface RfqVendor {
  id: number;
  rfqId: number;
  vendorId: number;
  vendorName?: string;
  invitedAt?: string;
  invitedBy?: number;
  responseStatus: VendorResponseStatus;
  portalToken?: string;
  tokenExpiresAt?: string;
  quotationId?: number;
}

// ─── Quotation ───────────────────────────────────────────────────────────────

export type QuotationEntryMode = 'MANUAL' | 'PORTAL' | 'EMAIL_OCR';
export type QuotationStatus = 'RECEIVED' | 'ACCEPTED' | 'REJECTED' | 'WITHDRAWN';

export interface Quotation {
  id: number;
  quotationNo: string;
  rfqId: number;
  vendorId: number;
  vendorName?: string;
  receivedAt: string;
  validUntil?: string;
  currencyCode: string;
  freightAmount: number;
  freightBasis?: string;
  loadingAmount: number;
  otherCharges: number;
  discountAmount: number;
  discountPct?: number;
  paymentTerms?: string;
  deliveryDays?: number;
  warrantyTerms?: string;
  totalBasic: number;
  totalTax: number;
  totalValue: number;
  enteredBy: number;
  entryMode: QuotationEntryMode;
  fileId?: number;
  status: QuotationStatus;
  isLate: boolean;
  lateReason?: string;
  items?: QuotationItem[];
}

export interface QuotationItem {
  id: number;
  quotationId: number;
  rfqIndentMapId: number;
  quotedQty: number;
  uom: string;
  basicRate: number;
  discountPct: number;
  taxRatePct?: number;
  hsnCode?: string;
  landedRate: number; // computed: basic - discount + apportioned freight + apportioned other charges + non-creditable tax
  makeOffered?: string;
  deviationNote?: string;
  isTechnicallyAccepted: boolean;
  technicalRemark?: string;
  // Additional computed fields
  itemName?: string;
  itemCode?: string;
  apportionedFreight?: number;
  apportionedOtherCharges?: number;
  nonCreditableTax?: number;
}

// ─── Comparative Statement ───────────────────────────────────────────────────

export type EvaluationBasis = 'L1_ITEMWISE' | 'L1_TOTAL' | 'QCBS' | 'LIFECYCLE';
export type ComparativeStatus = 'DRAFT' | 'PENDING_APPROVAL' | 'APPROVED' | 'REJECTED' | 'NEGOTIATION_IN_PROGRESS';

export interface Comparative {
  id: number;
  csNo: string;
  rfqId: number;
  preparedBy?: number;
  preparedAt?: string;
  evaluationBasis: EvaluationBasis;
  technicalWeight?: number; // for QCBS
  commercialWeight?: number; // for QCBS
  status: ComparativeStatus;
  approvedBy?: number;
  approvedAt?: string;
  negotiationRound: number;
  recommendations?: ComparativeRecommendation[];
  // Matrix data
  vendorMatrix?: VendorComparativeData[];
}

export interface ComparativeRecommendation {
  id: number;
  comparativeId: number;
  rfqIndentMapId: number;
  recommendedVendorId: number;
  recommendedVendorName?: string;
  recommendedQty: number;
  recommendedRate: number;
  isLowest: boolean;
  deviationReason?: string; // MANDATORY when isLowest = false
  savingVsBudget?: number;
  savingVsLastPurchase?: number;
  // Additional fields
  itemName?: string;
  itemCode?: string;
  allQuotes?: VendorQuoteForItem[];
}

export interface VendorComparativeData {
  vendorId: number;
  vendorName: string;
  quotationId: number;
  totalValue: number;
  deliveryDays: number;
  paymentTerms: string;
  vendorScorecard?: number; // from Part 12
  isTechnicallyAccepted: boolean;
  itemQuotes: VendorQuoteForItem[];
}

export interface VendorQuoteForItem {
  rfqIndentMapId: number;
  itemName: string;
  itemCode: string;
  quotedQty: number;
  landedRate: number;
  totalValue: number;
  isLowest: boolean;
  rank: number; // 1, 2, 3...
  lastPurchaseRate?: number;
  budgetRate?: number;
  varianceVsBudget?: number;
  varianceVsLastPurchase?: number;
}

export interface NegotiationRound {
  roundNo: number;
  negotiatedAt: string;
  negotiatedBy: number;
  vendorId: number;
  revisedRates: Array<{
    rfqIndentMapId: number;
    oldRate: number;
    newRate: number;
    saving: number;
  }>;
  notes?: string;
}

// ─── Purchase Order ──────────────────────────────────────────────────────────

export type PoType = 'REGULAR' | 'RATE_CONTRACT_RELEASE' | 'SERVICE' | 'CAPEX' | 'IMPORT';
export type PoStatus = 'DRAFT' | 'PENDING_APPROVAL' | 'APPROVED' | 'RELEASED' | 'PARTIALLY_RECEIVED' | 'RECEIVED' | 'CLOSED' | 'SHORT_CLOSED' | 'CANCELLED';
export type PoClosureStatus = 'FULLY_RECEIVED' | 'SHORT_CLOSED' | 'CANCELLED';
export type AmendmentType = 'QTY' | 'RATE' | 'DATE' | 'SPEC' | 'TERMS' | 'CANCEL' | 'SHORT_CLOSE';

export interface PoExtension {
  poId: number;
  comparativeId?: number;
  rateContractId?: number;
  projectId: number;
  wbsId?: number;
  costCodeId?: number;
  poType: PoType;
  deliveryLocationId?: number;
  incoterm?: string;
  qtyTolerancePct?: number;
  valueTolerancePct?: number;
  advancePct?: number;
  advancePaid?: number;
  retentionPct?: number;
  ldClause?: string;
  warrantyMonths?: number;
  budgetStatus?: BudgetStatus;
  budgetOverrideBy?: number;
  budgetOverrideReason?: string;
  vendorComplianceOk: boolean;
  complianceCheckedAt?: string;
  releasedAt?: string;
  releasedBy?: number;
  acknowledgedAt?: string;
  acknowledgementRef?: string;
  closureStatus?: PoClosureStatus;
  closedAt?: string;
  closureReason?: string;
}

export interface PoDeliverySchedule {
  id: number;
  poItemId: number;
  scheduleNo: number;
  scheduledDate: string;
  scheduledQty: number;
  deliveredQty: number;
  status: 'PENDING' | 'PARTIAL' | 'DELIVERED' | 'OVERDUE' | 'REVISED';
  revisedDate?: string;
  revisionReason?: string;
  isOverdue: boolean;
  daysOverdue?: number;
}

export interface PoAmendment {
  id: number;
  poId: number;
  amendmentNo: number;
  amendmentType: AmendmentType;
  reason: string;
  beforeSnapshot: any; // JSON
  afterSnapshot: any; // JSON
  valueImpact: number;
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  requestedBy: number;
  requestedAt: string;
  approvedBy?: number;
  approvedAt?: string;
}

export interface PoReleaseGate {
  gateName: string;
  status: 'PASS' | 'FAIL';
  message: string;
  details?: any;
}

export interface PoReleaseValidation {
  canRelease: boolean;
  gates: PoReleaseGate[];
  failedGates: string[];
}

// ─── Rate Contract ───────────────────────────────────────────────────────────

export type RateContractStatus = 'DRAFT' | 'ACTIVE' | 'EXPIRED' | 'EXHAUSTED' | 'CANCELLED';

export interface RateContract {
  id: number;
  contractNo: string;
  vendorId: number;
  vendorName?: string;
  projectId?: number;
  companyId: number;
  effectiveFrom: string;
  effectiveTo: string;
  valueCeiling?: number;
  quantityCeiling?: number;
  consumedValue: number;
  consumedQuantity: number;
  status: RateContractStatus;
  approvedBy?: number;
  approvedAt?: string;
  items: RateContractItem[];
  releases: RateContractRelease[];
}

export interface RateContractItem {
  id: number;
  contractId: number;
  itemId: number;
  itemName?: string;
  itemCode?: string;
  uom: string;
  rate: number;
  maxQuantity?: number;
  consumedQuantity: number;
}

export interface RateContractRelease {
  id: number;
  contractId: number;
  poId: number;
  poNo?: string;
  releasedAt: string;
  releasedBy: number;
  value: number;
  items: Array<{
    itemId: number;
    quantity: number;
    rate: number;
    value: number;
  }>;
}

// ─── Automation ──────────────────────────────────────────────────────────────

export interface AutoGeneratedIndent {
  sourceType: 'MATERIAL_REQUIREMENT_PLAN' | 'REORDER_LEVEL';
  sourceId: number;
  projectId: number;
  items: Array<{
    itemId: number;
    quantity: number;
    requiredByDate: string;
  }>;
  generatedAt: string;
  generatedBy: number; // system user
}

export interface VendorSuggestion {
  vendorId: number;
  vendorName: string;
  score: number; // 0-100
  reasons: string[];
  // e.g., "Approved vendor", "Category match", "Scorecard rank: 2", "Last delivery: on-time"
}

export interface PriceTrend {
  itemId: number;
  itemName: string;
  dataPoints: Array<{
    date: string;
    rate: number;
    poNo: string;
    vendorName: string;
  }>;
  trendDirection: 'UP' | 'DOWN' | 'STABLE';
  trendPct: number; // percentage change over last 6 months
}

// ─── API Request/Response Types ──────────────────────────────────────────────

export interface CreateIndentRequest {
  projectId: number;
  wbsId?: number;
  costCodeId?: number;
  indentType: IndentType;
  requiredByDate: string;
  justification?: string;
  items: Array<{
    itemId: number;
    quantity: number;
    specification?: string;
    makePreference?: string;
  }>;
}

export interface ValidateIndentResponse {
  validation: IndentValidation;
  canProceed: boolean;
  warnings: string[];
  errors: string[];
}

export interface CreateRfqRequest {
  projectId?: number;
  rfqType: RfqType;
  title: string;
  scopeSummary?: string;
  dueDatetime: string;
  isSealed: boolean;
  deliveryTerms?: string;
  paymentTerms?: string;
  indentItemIds: number[];
  vendorIds: number[];
}

export interface SubmitQuotationRequest {
  rfqId: number;
  vendorId: number;
  validUntil?: string;
  currencyCode: string;
  freightAmount: number;
  freightBasis?: string;
  loadingAmount: number;
  otherCharges: number;
  discountAmount: number;
  discountPct?: number;
  paymentTerms?: string;
  deliveryDays?: number;
  warrantyTerms?: string;
  items: Array<{
    rfqIndentMapId: number;
    quotedQty: number;
    uom: string;
    basicRate: number;
    discountPct: number;
    taxRatePct?: number;
    hsnCode?: string;
    makeOffered?: string;
    deviationNote?: string;
  }>;
}

export interface ComputeLandedRateRequest {
  basicRate: number;
  discountPct: number;
  freightAmount: number;
  freightBasis: 'VALUE' | 'QUANTITY' | 'WEIGHT';
  otherCharges: number;
  taxRatePct: number;
  isCreditableGst: boolean;
  totalQuotationValue: number;
  itemQuantity: number;
}

export interface ComputeLandedRateResponse {
  landedRate: number;
  apportionedFreight: number;
  apportionedOtherCharges: number;
  nonCreditableTax: number;
  breakdown: {
    basic: number;
    discount: number;
    freight: number;
    otherCharges: number;
    tax: number;
  };
}

export interface GenerateComparativeRequest {
  rfqId: number;
  evaluationBasis: EvaluationBasis;
  technicalWeight?: number;
  commercialWeight?: number;
}

export interface ReleasePoRequest {
  poId: number;
  overrideBudget?: boolean;
  budgetOverrideReason?: string;
}

export interface ValidatePoReleaseResponse {
  validation: PoReleaseValidation;
  canRelease: boolean;
  blockedBy: string[];
}

export interface CreateAmendmentRequest {
  poId: number;
  amendmentType: AmendmentType;
  reason: string;
  changes: any; // depends on amendment type
}

export interface ConsumeRateContractRequest {
  contractId: number;
  poId: number;
  items: Array<{
    itemId: number;
    quantity: number;
    rate: number;
  }>;
}

export interface ValidateRateContractResponse {
  canConsume: boolean;
  remainingValue: number;
  remainingQuantity: number;
  isExpired: boolean;
  errors: string[];
}

// ─── KPI Types ───────────────────────────────────────────────────────────────

export interface ProcurementKpis {
  indentsPendingApproval: number;
  indentToPoCycleDays: number;
  poValueCommitted: number;
  poValueOpen: number;
  budgetVsCommittedVsActual: {
    budget: number;
    committed: number;
    actual: number;
  };
  savingsVsBudget: number;
  savingsVsLastPurchase: number;
  singleSourcePct: number;
  l1DeviationPct: number;
  vendorResponseRate: number;
  quotationTurnaroundDays: number;
  overdueDeliveries: number;
  poAmendmentRate: number;
  rateContractUtilizationPct: number;
}

// ─── Report Types ────────────────────────────────────────────────────────────

export interface IndentRegisterReport {
  indents: Array<{
    indentNo: string;
    projectId: number;
    projectName: string;
    indentType: IndentType;
    status: IndentStatus;
    totalValue: number;
    createdDate: string;
    requiredByDate: string;
    ageDays: number;
    approvedDate?: string;
  }>;
}

export interface PoRegisterReport {
  pos: Array<{
    poNo: string;
    projectId: number;
    projectName: string;
    vendorId: number;
    vendorName: string;
    poType: PoType;
    status: PoStatus;
    totalValue: number;
    orderDate: string;
    deliveryDate?: string;
    receivedValue: number;
    balanceValue: number;
    ageDays: number;
  }>;
}

export interface SavingsAnalysisReport {
  period: string;
  totalPoValue: number;
  totalBudgetValue: number;
  totalLastPurchaseValue: number;
  savingsVsBudget: number;
  savingsVsBudgetPct: number;
  savingsVsLastPurchase: number;
  savingsVsLastPurchasePct: number;
  byCategory: Array<{
    category: string;
    poValue: number;
    budgetValue: number;
    savings: number;
    savingsPct: number;
  }>;
}

export interface VendorPerformanceReport {
  vendorId: number;
  vendorName: string;
  totalPos: number;
  totalValue: number;
  onTimeDeliveryPct: number;
  qualityRejectionPct: number;
  avgQuotationTurnaroundDays: number;
  responseRate: number;
  scorecardScore: number;
}
